config/routes.rb
Rails.application.routes.draw do

  resources :languages
  root 'welcome#index'
  get 'ask', to: 'ask#index'
  post 'ask', to: 'ask#create'
  get 'user', to: 'user#index'
  get 'teach', to: 'teach#index'
  get 'learn', to: 'learn#index'
  get 'options', to: 'options#index'
  post 'options', to: 'options#create'
  get 'languages', to: 'languages#index'
  get 'notifications', to: 'notifications#index'
  # get 'bookmarks', to: 'notifications#index'
  # get 'posts', to: 'posts#index'

  # Para testes:
  resources :mother_languages
  resources :languages
  resources :author_comment_posts
  resources :bookmarks
  resources :comments do
    member do
      get :change_upvote
    end
  end
  resources :posts
  resources :learning_languages
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates_presence_of :text
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  def change_upvote
    comment = Comment.find(params[:id])
    acp = AuthorCommentPost.find_by(:comment_id => comment.id)
    post = Post.find_by(:id => acp.post.id)

    # Updates the upvoted comments count of post
    if comment.upvoted == false
      post.upvotes += 1
    else
      post.upvotes -= 1
    end

    comment.upvoted = !comment.upvoted # flop the status
    comment.save
    post.save
    redirect_to post_path(id: post, pg: params[:pg])
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    params[:status]
    if params[:text].blank?
      redirect_to post_path(params[:post_id]), notice: t('comment_mis')
    else
      @comment = Comment.new(text: params[:text], upvoted: false)
      @comment.save!

      @user = User.find_by(:id => params[:user_id])
      @post = Post.find_by(:id => params[:post_id])

      @author_comment = AuthorCommentPost.new(user: @user, post: @post, comment: @comment)
      @author_comment.save!
      redirect_to post_path(id: @post, pg: -1), notice: t('successfully_commented')
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: t('successfully_commented') }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    if AuthorCommentPost.where(user_id: current_user, post_id: params[:post_id], comment_id: params[:comment_id]).count > 0
      AuthorCommentPost.find_by(user_id: current_user, post_id: params[:post_id], comment_id: params[:comment_id]).destroy
      Comment.find_by(id: params[:comment_id]).destroy
    end
    redirect_to post_path(id: params[:post_id], pg: params[:pg]), notice: t('successfully_comment_del')

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:upvotes, :text, :pg)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :upvotes %>
    <%= form.number_field :upvotes %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Upvotes</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.upvotes %></td>
        <td><%= comment.text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Upvotes:</strong>
  <%= @comment.upvotes %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>