config/routes.rb
Rails.application.routes.draw do

  resources :languages
  root 'welcome#index'
  get 'ask', to: 'ask#index'
  post 'ask', to: 'ask#create'
  get 'user', to: 'user#index'
  get 'teach', to: 'teach#index'
  get 'learn', to: 'learn#index'
  get 'options', to: 'options#index'
  post 'options', to: 'options#create'
  get 'languages', to: 'languages#index'
  get 'notifications', to: 'notifications#index'
  # get 'bookmarks', to: 'notifications#index'
  # get 'posts', to: 'posts#index'

  # Para testes:
  resources :mother_languages
  resources :languages
  resources :author_comment_posts
  resources :bookmarks
  resources :comments do
    member do
      get :change_upvote
    end
  end
  resources :posts
  resources :learning_languages
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author_comment_post.rb
class AuthorCommentPost < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  belongs_to :post
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user, uniqueness: { scope: :post }
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates_presence_of :text
end

app/models/language.rb
class Language < ApplicationRecord
  validates_presence_of :idiom
end

app/models/learning_language.rb
class LearningLanguage < ApplicationRecord
  belongs_to :user
  belongs_to :language
end

app/models/mother_language.rb
class MotherLanguage < ApplicationRecord
  belongs_to :user
  belongs_to :language
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates_presence_of :difficulty
  validates_presence_of :learning_language
  validates_presence_of :mother_language
  validates_presence_of :title
  validates_presence_of :text
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :learning_langages
  has_one :mother_langages
  validates_presence_of :username, :password, :email
  validates_uniqueness_of :username
  
  def login=(login)
      @login = login
  end

  def login
     @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

end

app/controllers/ask_controller.rb
class AskController < ApplicationController
  before_action :authenticate_user!
  def index
    @post = Post.new
    @learningLanguage = LearningLanguage.where(:user => current_user.id)
    @motherLanguage = MotherLanguage.where(:user => current_user.id)
    if @learningLanguage.count == 0 || @motherLanguage.count == 0
     redirect_to options_path, notice: t('missing_lang')
    end
  end

  def create
    params[:ask]['user_id'] = current_user.id
    params[:ask]['upvotes'] = 0
    if params[:ask][:title].blank?
      @post = Post.new
      @learningLanguage = LearningLanguage.where(:user => current_user.id)
      @motherLanguage = MotherLanguage.where(:user => current_user.id)
      redirect_to ask_path, notice: t('missing_tit')
    elsif params[:ask][:text].blank?
      @post = Post.new
      @learningLanguage = LearningLanguage.where(:user => current_user.id)
      @motherLanguage = MotherLanguage.where(:user => current_user.id)
      redirect_to ask_path, notice: t('missing_txt')
    else
      @post = Post.new(ask_params)


      respond_to do |format|
        if @post.save
          bookmark = Bookmark.new(user_id: current_user.id, post_id: @post.id)
          bookmark.save!
            format.html { redirect_to @post, notice: t('successfully_created') }
            format.json { render :show, status: :created, location: @post }
        else
          format.html { render :index }
        end
      end
    end
  end


  def ask_params
    params.require(:ask).permit( :difficulty, :learning_language, :mother_language, :title, :text, :upvotes, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ask_helper.rb
module AskHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teach_helper.rb
module TeachHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/templates/_ads.html.erb
<div class="ads">
  <h2><%= t 'Ads' %></h2>
  <h3><%= t 'Some_ads' %></h3>
  <div class="fakeimg" style="height:200px;"><%= t 'Ads_Image' %></div>
  <h4><%= t('Look') %></h4>
</div>

app/views/templates/_footer.html.erb
<div class="footer">
	<br>
	<h2 align="center"><%= t 'making' %></h2>
	<h4 align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= t 'copy' %></h4>
</div>

app/views/templates/_header.html.erb
<% content_for :header do -%>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag '/css/header' %>
	<%= stylesheet_link_tag '/css/content' %>
	<%= stylesheet_link_tag '/css/navbar' %>
	<%= stylesheet_link_tag '/css/posts' %>
	<%= stylesheet_link_tag '/css/notifications' %>
	<%= stylesheet_link_tag '/css/footer' %>
<% end -%>

<!-- Note -->

<!-- Header -->
<div class="header">
	lingui.me
</div>

app/views/templates/_navbar.html.erb
<div class="navbar">
  <%= link_to t("learn"), learn_path(dif: 1), class: "btn-navbar" %>
  <%= link_to t("teach"), teach_path(), class: "btn-navbar" %>
  <% if user_signed_in? %>
    <%= link_to t("me"), user_path(id: current_user.id),class: "btn-navbar" %>
  <% end %>
  <%= link_to t("options"), options_path(), class: "btn-navbar" %>
  <%= link_to t('logout'), destroy_user_session_path, method: :delete, class: "btn-navbar" %>
</div>

app/views/templates/_notifications.html.erb
<div class="notif">
  <p align='center'>
    <%= link_to t("ask_your_question"), ask_path(), class: "CreatePostLink"%>
  </p>
  <hr class="PostBarLink">
  <h2 align="center"><b><%= t 'your_notifications' %></b></h2>
  <hr class="notificationshr1">

  <%  AuthorCommentPost.where(post_id: Bookmark.where(:user_id => current_user.id).pluck(:post_id)).includes(:user, :post, :comment).order("created_at DESC").take(7).each do |acp|  %>
    <div class="notifications">
      <div class="notificationsDate"><%= acp.created_at.strftime(t('date')) %></div>
      <div class="PostDescription"><%= link_to acp.user.username, user_path(id: acp.user.id), class: "PostDescriptionLink" %>
      <%= t 'responded' %> <%= link_to t("a_bookmarked_question"), post_path(id: acp.post_id, pg: -1), class: "notificationsLink" %>:<br>
      </div>
      <div class="notificationsBox">
      <%= acp.comment.text %>
      </div>
    </div>
    <hr class="notificationshr1">
  <% end %>
  <h2 align="center"><b><%= link_to t("see_more"), notifications_path(), class: "notificationsLink" %></h2>

  </div>
</div>