config/routes.rb
Rails.application.routes.draw do

  resources :languages
  root 'welcome#index'
  get 'ask', to: 'ask#index'
  post 'ask', to: 'ask#create'
  get 'user', to: 'user#index'
  get 'teach', to: 'teach#index'
  get 'learn', to: 'learn#index'
  get 'options', to: 'options#index'
  post 'options', to: 'options#create'
  get 'languages', to: 'languages#index'
  get 'notifications', to: 'notifications#index'
  # get 'bookmarks', to: 'notifications#index'
  # get 'posts', to: 'posts#index'

  # Para testes:
  resources :mother_languages
  resources :languages
  resources :author_comment_posts
  resources :bookmarks
  resources :comments do
    member do
      get :change_upvote
    end
  end
  resources :posts
  resources :learning_languages
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author_comment_post.rb
class AuthorCommentPost < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  belongs_to :post
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user, uniqueness: { scope: :post }
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates_presence_of :text
end

app/models/language.rb
class Language < ApplicationRecord
  validates_presence_of :idiom
end

app/models/learning_language.rb
class LearningLanguage < ApplicationRecord
  belongs_to :user
  belongs_to :language
end

app/models/mother_language.rb
class MotherLanguage < ApplicationRecord
  belongs_to :user
  belongs_to :language
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates_presence_of :difficulty
  validates_presence_of :learning_language
  validates_presence_of :mother_language
  validates_presence_of :title
  validates_presence_of :text
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :learning_langages
  has_one :mother_langages
  validates_presence_of :username, :password, :email
  validates_uniqueness_of :username
  
  def login=(login)
      @login = login
  end

  def login
     @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

end

app/controllers/ask_controller.rb
class AskController < ApplicationController
  before_action :authenticate_user!
  def index
    @post = Post.new
    @learningLanguage = LearningLanguage.where(:user => current_user.id)
    @motherLanguage = MotherLanguage.where(:user => current_user.id)
    if @learningLanguage.count == 0 || @motherLanguage.count == 0
     redirect_to options_path, notice: t('missing_lang')
    end
  end

  def create
    params[:ask]['user_id'] = current_user.id
    params[:ask]['upvotes'] = 0
    if params[:ask][:title].blank?
      @post = Post.new
      @learningLanguage = LearningLanguage.where(:user => current_user.id)
      @motherLanguage = MotherLanguage.where(:user => current_user.id)
      redirect_to ask_path, notice: t('missing_tit')
    elsif params[:ask][:text].blank?
      @post = Post.new
      @learningLanguage = LearningLanguage.where(:user => current_user.id)
      @motherLanguage = MotherLanguage.where(:user => current_user.id)
      redirect_to ask_path, notice: t('missing_txt')
    else
      @post = Post.new(ask_params)


      respond_to do |format|
        if @post.save
          bookmark = Bookmark.new(user_id: current_user.id, post_id: @post.id)
          bookmark.save!
            format.html { redirect_to @post, notice: t('successfully_created') }
            format.json { render :show, status: :created, location: @post }
        else
          format.html { render :index }
        end
      end
    end
  end


  def ask_params
    params.require(:ask).permit( :difficulty, :learning_language, :mother_language, :title, :text, :upvotes, :user_id)
  end

end

app/controllers/author_comment_posts_controller.rb
class AuthorCommentPostsController < ApplicationController
  before_action :authenticate_user!, :set_author_comment_post, only: [:show, :edit, :update, :destroy]

  # GET /author_comment_posts
  # GET /author_comment_posts.json
  def index
    @author_comment_posts = AuthorCommentPost.all
  end

  # GET /author_comment_posts/1
  # GET /author_comment_posts/1.json
  def show
  end

  # GET /author_comment_posts/new
  def new
    @author_comment_post = AuthorCommentPost.new
  end

  # GET /author_comment_posts/1/edit
  def edit
  end

  # POST /author_comment_posts
  # POST /author_comment_posts.json
  def create
    @author_comment_post = AuthorCommentPost.new(author_comment_post_params)

    respond_to do |format|
      if @author_comment_post.save
        format.html { redirect_to @author_comment_post, notice: 'Author comment post was successfully created.' }
        format.json { render :show, status: :created, location: @author_comment_post }
      else
        format.html { render :new }
        format.json { render json: @author_comment_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /author_comment_posts/1
  # PATCH/PUT /author_comment_posts/1.json
  def update
    respond_to do |format|
      if @author_comment_post.update(author_comment_post_params)
        format.html { redirect_to @author_comment_post, notice: 'Author comment post was successfully updated.' }
        format.json { render :show, status: :ok, location: @author_comment_post }
      else
        format.html { render :edit }
        format.json { render json: @author_comment_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /author_comment_posts/1
  # DELETE /author_comment_posts/1.json
  def destroy
    @author_comment_post.destroy
    respond_to do |format|
      format.html { redirect_to author_comment_posts_url, notice: 'Author comment post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author_comment_post
      @author_comment_post = AuthorCommentPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_comment_post_params
      params.require(:author_comment_post).permit(:user_id, :comment_id, :post_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def index
    vars = request.query_parameters
    @id = vars['id']
    if(!defined? @id)
      @id = current_user.id
    end
    @contagem = 0
    @user = User.find_by(:id => @id)
    allposts = Post.where(:user => @user).order("created_at DESC")

    @pg = vars['pg']
    if(@pg.blank?)
      @pg = 0
    end
    @pg = @pg.to_i
    if @pg < 0
      @pg = 0
    end
    @posts = []
    i = @pg * 5
    total = allposts.count
    @primeira_pagina = false
    if @pg == 0 || total < 4
      @primeira_pagina = true
    end
    @ultima_pagina = false
    if total >= i + 5
      for j in 0..4
        @posts.push(allposts[i])
        i += 1
      end
    else
      while i < total
        @posts.push(allposts[i])
        i += 1
      end
      @ultima_pagina = true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ask_helper.rb
module AskHelper
end

app/helpers/author_comment_posts_helper.rb
module AuthorCommentPostsHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teach_helper.rb
module TeachHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/author_comment_posts/_form.html.erb
<%= form_with(model: author_comment_post, local: true) do |form| %>
  <% if author_comment_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author_comment_post.errors.count, "error") %> prohibited this author_comment_post from being saved:</h2>

      <ul>
      <% author_comment_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :comment_id %>
    <%= form.text_field :comment_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/author_comment_posts/edit.html.erb
<h1>Editing Author Comment Post</h1>

<%= render 'form', author_comment_post: @author_comment_post %>

<%= link_to 'Show', @author_comment_post %> |
<%= link_to 'Back', author_comment_posts_path %>

app/views/author_comment_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Author Comment Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Comment</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @author_comment_posts.each do |author_comment_post| %>
      <tr>
        <td><%= author_comment_post.user %></td>
        <td><%= author_comment_post.comment %></td>
        <td><%= author_comment_post.post %></td>
        <td><%= link_to 'Show', author_comment_post %></td>
        <td><%= link_to 'Edit', edit_author_comment_post_path(author_comment_post) %></td>
        <td><%= link_to 'Destroy', author_comment_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author Comment Post', new_author_comment_post_path %>

app/views/author_comment_posts/new.html.erb
<h1>New Author Comment Post</h1>

<%= render 'form', author_comment_post: @author_comment_post %>

<%= link_to 'Back', author_comment_posts_path %>

app/views/author_comment_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @author_comment_post.user %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @author_comment_post.comment %>
</p>

<p>
  <strong>Post:</strong>
  <%= @author_comment_post.post %>
</p>

<%= link_to 'Edit', edit_author_comment_post_path(@author_comment_post) %> |
<%= link_to 'Back', author_comment_posts_path %>