config/routes.rb
Rails.application.routes.draw do

  resources :languages
  root 'welcome#index'
  get 'ask', to: 'ask#index'
  post 'ask', to: 'ask#create'
  get 'user', to: 'user#index'
  get 'teach', to: 'teach#index'
  get 'learn', to: 'learn#index'
  get 'options', to: 'options#index'
  post 'options', to: 'options#create'
  get 'languages', to: 'languages#index'
  get 'notifications', to: 'notifications#index'
  # get 'bookmarks', to: 'notifications#index'
  # get 'posts', to: 'posts#index'

  # Para testes:
  resources :mother_languages
  resources :languages
  resources :author_comment_posts
  resources :bookmarks
  resources :comments do
    member do
      get :change_upvote
    end
  end
  resources :posts
  resources :learning_languages
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates_presence_of :difficulty
  validates_presence_of :learning_language
  validates_presence_of :mother_language
  validates_presence_of :title
  validates_presence_of :text
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @id = params[:id]
    @post = Post.find_by(:id => @id)
    allacp = AuthorCommentPost.where(:post_id => @id).includes(:user, :comment)
    @bookmarked = false;
    if Bookmark.where(user_id: current_user.id, post_id: @id).count > 0
      @bookmarked = true
    end

    vars = request.query_parameters
    @pg = vars['pg']
    if(@pg.blank?)
      @pg = 0
    end
    @pg = @pg.to_i
    if @pg < -1
      @pg = 0
    end
    @acp = []
    total = allacp.count

    # First Page
    if @pg != -1
      i = @pg * 7
      @primeira_pagina = false
      if @pg == 0 || total < 4
        @primeira_pagina = true
      end
      @ultima_pagina = false
      if total >= i + 7
        for j in 0..6
          @acp.push(allacp[i])
          i += 1
        end
      else
        while i < total
          @acp.push(allacp[i])
          i += 1
        end
        @ultima_pagina = true
      end
    # Last page
    else
      @ultima_pagina = true
      @primeira_pagina = true
      if total > 7
        @primeira_pagina = false
      end

      j = total - total%7
      while j < total
        @acp.push(allacp[j])
        j += 1
      end

      @pq = (total-total%7)/7
      puts "-----------------------------------------------------------------"
      puts @pg
      puts "-----------------------------------------------------------------"
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:upvotes, :user_id, :difficulty, :learning_language, :mother_language, :title, :text)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :upvotes %>
    <%= form.number_field :upvotes %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :difficulty %>
    <%= form.number_field :difficulty %>
  </div>

  <div class="field">
    <%= form.label :learning_language %>
    <%= form.text_field :learning_language %>
  </div>

  <div class="field">
    <%= form.label :mother_language %>
    <%= form.text_field :mother_language %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Upvotes</th>
      <th>User</th>
      <th>Difficulty</th>
      <th>Learning language</th>
      <th>Mother language</th>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.upvotes %></td>
        <td><%= post.user %></td>
        <td><%= post.difficulty %></td>
        <td><%= post.learning_language %></td>
        <td><%= post.mother_language %></td>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render ("/templates/navbar") %>
<div class="row">
  <%= render ("/templates/ads") %>
  <div class="main">
    <p id="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <a href="#" class="title">"<%= @post.title %>"</a><br>
    <div class="PostLanguage"><%= t('Question_of') %> <b><%= @post.learning_language %></b> -
      <% if @post.difficulty == 1 %>
        <%= t("beginner") %>
      <% elsif @post.difficulty == 2 %>
        <%= t("intermediate") %>
      <% else %>
        <%= t("advanced") %>
      <% end %>
    <br><%= t('Answer_in') %> <b><%= @post.mother_language %></b>
    </div>
    <div class="PostDescription"><%= t('Asked_by') %>
      <%= link_to @post.user.login, user_path(id: @post.user.id), class: "PostDescriptionLink" %>
       <%= t('in') %>
       <%= if params[:locale] == nil
          @post.created_at.strftime(t('date'))
        end %>
      <h3 align="left">
        <% if @bookmarked %>
          <%= link_to t('bookmarked'), bookmarks_path(post_id: @post.id, pg: @pg), class: "PostDescriptionLink" %>
        <% else %>
          <%= link_to t('bookmark'), bookmarks_path(post_id: @post.id, pg: @pg), class: "PostDescriptionLink" %>
        <% end %>
      </h3>
    </div>
    <div class="questionsBox">
      <%= @post.text %>
    </div>
    <p>
      <% if @primeira_pagina == false %>
        <span style="float:left;"><%= link_to t('newer_comment'), post_path(post_id: @post.id, pg: @pg-1), class: "notificationsLink" %></span>
      <% end %>
      <% if @ultima_pagina == false %>
        <span style="float:right;"><%= link_to t('older_comment'), post_path(post_id: @post.id, pg: @pg+1), class: "notificationsLink" %></span>
      <% end %>
    </p><br>
    <hr class="PostBarLink">
    <% @acp.each do |acp| %>
      <div class="commentBox">
        <%= link_to acp.user.username, user_path(id: acp.user.id), class: "PostDescriptionLink" %> <%= t('at') %> <%= acp.created_at.strftime(t('date')) %><br>
        <h3>
          <%= acp.comment.text %>
        </h3>
        <% if acp.user_id != current_user.id %>
          <% if acp.comment.upvoted%>
            <%= link_to t('upvoted'), change_upvote_comment_path(id: acp.comment.id, pg: @pg), class: "UpvoteLinkTrue" %>
          <% else %>
            <%= link_to t('upvote'), change_upvote_comment_path(id: acp.comment.id, pg: @pg), class: "UpvoteLinkFalse" %>
          <% end %>
        <% end %>
        <% if acp.user.id == current_user.id %>
          <%= link_to t('Delete'), {:controller => "comments", action: :destroy,
            comment_id: acp.comment_id, post_id: acp.post_id, pg: @pg }, method: :delete,
            data: { confirm:  t('Are_you_sure') }, class: "PostDeleteLink" %>

        <% end %>
      </div>
    <%end%>
    <br>
    <p>
      <% if @primeira_pagina == false %>
        <span style="float:left;"><%= link_to t('newer_comment'), post_path(post_id: @post.id, pg: @pg-1), class: "notificationsLink" %></span>
      <% end %>
      <% if @ultima_pagina == false %>
        <span style="float:right;"><%= link_to t('older_comment'), post_path(post_id: @post.id, pg: @pg+1), class: "notificationsLink" %></span>
      <% end %>

    </p><br><hr class="PostBarLink">

    <%= form_with url: comments_path do |form|%>
      <div class="commentBox">
        <%= form.hidden_field :post_id, value: @post.id %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.text_area :text, id: "question"%>
        <%= form.submit t('Comment_btn') %>
      </div>
    <% end %>

</div>
<%= render ("/templates/notifications") %>
</div>
<!-- <%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %> -->